### ISSUE TITLE
 Chain Responsibility 

### ISSUE THREAD

**Issue by josephinoo** [axvargas/taller08#1]
Hola soy Joseph Avila , revisaba tu proyecto observe que se podría aplicar este patron para manejar el dinero del cajero automático:

Implementar el patrón **Chain Responsibility**  en el sistema ,ya que puede que se lleve acaba la trasaccion mediante una serie de manejadores para poder realizar un una transaccion
Motivación: En el momento de depositar y retirar dinero, el cajero automática debe realizar una cadena de manejadores , para implementar la solicitud . ATM tiene varios manejadores de dinero como manejadores de $ 500, $ 100  y  $ 50. Supongamos que si está intentando retirar $ 650  de un cajero automático, esa solicitud se enviará al administrador de  $ 500. Maneja una parte de la solicitud y reenvía la solicitud a otros manejadores como manejadores de  $ 100 y $ 50 . Finalmente, finalmente el cajero automatico  nos entrega la cantidad requerida.
 Sin aplicación del patrón:
 
 
![image](https://user-images.githubusercontent.com/46098690/89743030-e2825b00-da64-11ea-8ea3-6bcd73bb74c8.png)

**Aplicación del patrón Chain Responsibilty**
![image](https://user-images.githubusercontent.com/46098690/89743036-edd58680-da64-11ea-97bc-be5e6e2b1a8f.png)

 
 
 
 
 

**Consecuencias:**
Se crea una Solicitud con el monto solicitado. A continuación, se encadenan una serie de llamadas get , cada una manejando una denominación particular. Cada manejador determina el número de billetes de banco dispensados y resta esta cantidad de la cantidad restante. El objeto de solicitud se pasa a través de la cadena devolviendo esto en el método dispense .

**Comment by axvargas** [comment]
JAJAJAJA, son estudiantes diseño de software? justo este repo es de un taller de la materia. Creo que Chain of responsability no seria lo mejor, pero buen análisis. Éxitos!!!

**Comment by josephinoo** [comment]
thanks
