### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by josephinoo** [axvargas/taller08#2]
Hola soy Joseph Avila , revisaba tu proyecto observe que se podría aplicar este patron para manejar el dinero del cajero automático:

 Implementar el patrón Builder para la creación de cuentas complejas y paso a paso ,así nos permite producir distintos tipos de cuentas empleando el mismo código de construcción.
Motivación: 
Imaginemos al crear una cuenta  que requiera inicializarlo de una forma laboriosa que sea paso a paso , por que puede ser de Corriente , de Ahorros u otros , vamos a tener campos y cuentas anidadas. Normalmente, el código para inicializar  estará  sepultado dentro de un monstruoso constructor con una gran cantidad de parámetros,o peor puede estar disperso por todo el código cliente

Aplicación del patrón:
Debemos sacar  el código de construcción del objeto de su la clase Account y lo coloques dentro de objetos independientes ósea constructores,  Builder nos permite que instanciamos cuentas nuevas para cada cliente, con parámetros que nos de el cliente. Además de si hubiera diferentes tipos de cuenta, el builder estaría abierto a crear nuevos tipos de cuentas. Para este caso se creo la clase directora llamada AccountDirector ya que aquí definimos en el orden que se deber ejecutar los paso para construir la cuenta , la clase AccountBuilder, la clase ConcreteAccount.El patrón Builder nos permite construir Account paso a paso. Podemos  aplazar la ejecución de ciertos pasos sin descomponer el producto final

![image](https://user-images.githubusercontent.com/46098690/89852424-69fac780-db54-11ea-9fed-c02806c4dc1c.png) 
![image](https://user-images.githubusercontent.com/46098690/89852445-7a12a700-db54-11ea-9c99-2b7d8f99b22f.png)
![image](https://user-images.githubusercontent.com/46098690/89852451-7c750100-db54-11ea-83c3-99366013b76c.png)
![image](https://user-images.githubusercontent.com/46098690/89852461-81d24b80-db54-11ea-8d2a-8242ce16a5e2.png)

**Comment by axvargas** [comment]
Esté está mejor!!!, buen análisis gracias por la recomendación
